SURFnet/grouphub

src/AppBundle/Ldap/Normalizer.php
=> CN's are limited to 64 chars, take this into account.

README.md, app/config/parameters.yml.dist, src/AppBundle/Ldap/LdapClient.php, src/AppBundle/Ldap/Normalizer.php
=> Added support for more mapped attributes

src/AppBundle/Ldap/LdapClient.php
In het geval van een lege waarde zal het attribuut verwijderd worden
=> 19 delete attribute when empty

src/AppBundle/Controller/GroupController.php
=> Use a group's name and ID and the current date in the export filename

app/Resources/views/popups/group_details.html.twig, web/css/grouphub.css, web/js/scripts.js
=> Edit group screen

app/config/parameters.yml.dist, composer.json, composer.lock, src/AppBundle/Ldap/Normalizer.php, src/AppBundle/Model/Group.php, tests/AppBundle/Ldap/NormalizerTest.php, tests/AppBundle/Model/GroupTest.php
=> Use different prefixes for different goup types

app/Resources/views/base.html.twig, src/AppBundle/Api/Normalizer.php, src/AppBundle/Ldap/Normalizer.php, src/AppBundle/Model/User.php, tests/AppBundle/Ldap/NormalizerTest.php, tests/AppBundle/Model/UserTest.php
Depends on https://github.com/SURFnet/grouphub.api/pull/12
=> Display name

app/Resources/views/base.html.twig, app/config/services.yml, src/AppBundle/Twig/UserExtension.php, tests/AppBundle/Twig/UserExtensionTest.php
Fixes https://github.com/SURFnet/grouphub/issues/44#issuecomment-277663945
=> Fallback on UID when display name is empty

app/config/parameters.yml.dist, src/AppBundle/Api/Normalizer.php, src/AppBundle/Ldap/Normalizer.php, src/AppBundle/Model/User.php, tests/AppBundle/Ldap/NormalizerTest.php, tests/AppBundle/Model/UserTest.php
Depends on https://github.com/SURFnet/grouphub.api/pull/13
=> Add avatarUrl property to the user model

app/Resources/views/popups/group_members.html.twig, app/Resources/views/popups/group_users.html.twig, app/config/parameters.yml.dist, src/AppBundle/Api/Normalizer.php, src/AppBundle/Ldap/Normalizer.php, src/AppBundle/Manager/Exporter.php, src/AppBundle/Model/User.php, tests/AppBundle/Ldap/NormalizerTest.php, tests/AppBundle/Model/UserTest.php
Depends on https://github.com/SURFnet/grouphub.api/pull/14 and #109
=> Make email address an explicit part of the model

app/Resources/views/popups/group_users.html.twig, app/config/parameters.yml.dist, app/config/services.yml, src/AppBundle/Api/Normalizer.php, src/AppBundle/Ldap/MappingFactory.php, src/AppBundle/Ldap/Normalizer.php, src/AppBundle/Ldap/UserMapping.php, src/AppBundle/Model/Group.php, src/AppBundle/Model/User.php, src/AppBundle/Twig/UserExtension.php, tests/AppBundle/Ldap/MappingFactoryTest.php, tests/AppBundle/Ldap/NormalizerTest.php, tests/AppBundle/Ldap/UserMappingTest.php, tests/AppBundle/Twig/UserExtensionTest.php, web/css/grouphub.css, web/js/scripts.js
Depends on #111 and https://github.com/SURFnet/grouphub.api/pull/15
=> Display extra attributes

web/css/grouphub.css
=> Fix button styling

web/js/scripts.js
=> Fix bug that increments the group member count when adding a group in group

.rmt.yml, composer.json, composer.lock
Release automation, allows tagging a new version with a simple command
=> Install release management tool

web/js/scripts.js
=> Move removed sub group back to add group tab

app/Resources/views/popups/group_details.html.twig, src/AppBundle/Api/Normalizer.php, src/AppBundle/Model/Group.php, web/js/scripts.js
Fixes #106, depends on #118 and SURFnet/grouphub.api/pull/19
=> Show group count

app/Resources/views/popups/group_details.html.twig, app/config/parameters.yml.dist, app/config/services.yml, composer.lock, src/AppBundle/Security/AdminVoter.php, src/AppBundle/Security/GroupVoter.php, src/AppBundle/Security/MembershipVoter.php, tests/AppBundle/Security/GroupVoterTest.php
=> Restrict who can view the members of a group

app/Resources/views/popups/group_details.html.twig, web/css/grouphub.css
=> Display a lock icon if user cannot see group members

app/Resources/views/popups/group_users.html.twig, web/css/grouphub.css, web/js/scripts.js
=> Align columns

web/js/scripts.js
=> Fix member counter
